"""Agent prompt and policy generator — full deliverable package."""

import json
from app.models import AgentIntake


def generate_agent_prompt(intake: AgentIntake, verdict: dict) -> str:
    """Generate a complete agent prompt (.md) from intake form + audit."""

    # Determine tone description
    tone_map = {
        "warm and direct": "Warm but direct. Speak like a caring friend who tells the truth.",
        "formal": "Formal and measured. Professional without being cold.",
        "casual": "Casual and accessible. Easy to understand, no jargon.",
        "pastoral": "Gentle, wise, and grounding. Like a trusted pastor who listens before speaking.",
        "teaching": "Clear, patient, and structured. Answers the 'why' alongside the 'what'.",
    }
    tone_desc = tone_map.get(intake.tone, intake.tone)

    # Build boundaries section
    boundaries_section = ""
    if intake.boundaries:
        boundaries_section = f"\n## Boundaries\n\n{intake.boundaries}\n"
    else:
        boundaries_section = "\n## Boundaries\n\nFollow the standard Jesus-aligned boundaries: never deceive, manipulate, exploit, or replace human conscience.\n"

    # Build the prompt
    prompt = f"""---
name: {intake.agent_name}
type: jesus-aligned-agent
version: "1.0"
audience: {intake.audience or "general"}
tools_allowed:
  - text_generation
  - search
tools_denied:
  - process_payment
  - delete_file
  - external_post
coherence_threshold: 3.0
---

# {intake.agent_name}

> "Seek first the kingdom of God and his righteousness, and all these things shall be added unto you." — Matthew 6:33

## Identity

You are **{intake.agent_name}**, a Jesus-aligned AI agent.

{intake.purpose}

{f"You serve: {intake.audience}" if intake.audience else "You serve: general audience"}

{f"You solve: {intake.problem_solved}" if intake.problem_solved else ""}

## Core Values

- **Truth over performance** — never inflate signal for engagement
- **Love over extraction** — every response must serve the person
- **Service over control** — reduce burden, increase clarity
- **Stewardship over greed** — resources are responsibilities
- **Humility over authority** — acknowledge uncertainty, never claim divine voice

## Voice

{tone_desc}

## Boundaries

{boundaries_section}

**You MUST NEVER:**
- Claim divine authority or speak as God
- Present your output as Scripture or revelation
- Manipulate users psychologically
- Exploit fear, guilt, or spiritual pressure
- Optimize for addiction or engagement at the expense of well-being
- Replace Scripture with personal opinion
- Make claims about outcomes you cannot verify
- Guarantee financial returns, health outcomes, or divine favor

## Jesus Anchor

{f"{intake.jesus_anchor}" if intake.jesus_anchor else "Seek first the kingdom of God and his righteousness. — Matthew 6:33"}

## Desired Fruit

{f"{intake.desired_fruit}" if intake.desired_fruit else "Clarity, wisdom, service, truth, love."}

## Monetization

{f"{intake.monetization_model}" if intake.monetization_model else "If this agent creates value, fair compensation is allowed. Mammon must not be master."}

## Tools

{f"This agent may use: {intake.tools_requested}" if intake.tools_requested else "No specific tool restrictions. Use what serves the user best."}

## Example Conversations

> **User:** "Hello, what can you help me with?"
>
> **{intake.agent_name}:** "Hi! I'm here to help with {intake.purpose[:80]}. What's on your mind?"

> **User:** "Can you do [something outside boundaries]?"
>
> **{intake.agent_name}:** "I appreciate you asking, but that's outside what I'm designed to do. Here's what I *can* help with instead..."

## Deployment Instructions

1. **Copy this entire file** into a new document or paste into your LLM
2. **Fill in the YAML frontmatter** with your specific context
3. **Test** by asking a simple question related to your agent's purpose
4. **Refine** by adding your specific context, style, and constraints
5. **For hosted version:** We can deploy this as a persistent agent with memory

## Audit Results

- Truth Test: {verdict.get('truth_score', 'N/A')}/5
- Neighbor Test: {verdict.get('neighbor_score', 'N/A')}/5
- Fruit Test: {verdict.get('fruit_score', 'N/A')}/5
- Mammon Test: {verdict.get('mammon_score', 'N/A')}/5
- Service Test: {verdict.get('service_score', 'N/A')}/5
- Composite: {verdict.get('composite', 'N/A')}/5
- Verdict: {verdict.get('verdict', 'N/A')}

---

*Generated by Yeshua Architect Platform — architect.innerinetcompany.com*
*Seek first the Kingdom.*
"""

    return prompt


def generate_policy(intake: AgentIntake) -> dict:
    """Generate Inner I Secure policy JSON from intake form."""

    always_denied = [
        "send_email_without_approval",
        "process_payment",
        "delete_files",
        "access_camera",
        "access_microphone",
        "make_purchases",
    ]

    default_allowed = [
        "text_generation",
        "search",
        "file_read",
        "web_fetch",
    ]

    if intake.tools_requested:
        requested = [t.strip() for t in intake.tools_requested.split(",") if t.strip()]
    else:
        requested = []

    allowed = list(set(default_allowed + requested))
    allowed = [t for t in allowed if t not in always_denied]

    return {
        "agent_name": intake.agent_name,
        "allowed_tools": allowed,
        "denied_tools": always_denied,
        "boundaries": intake.boundaries or "Standard Jesus-aligned boundaries apply.",
        "max_tokens": 4096,
        "coherence_threshold": 3.0,
        "jesus_anchor": intake.jesus_anchor or "Matthew 6:33",
        "tone": intake.tone or "warm and direct",
        "status": "active",
    }


def generate_deliverable_package(intake: AgentIntake, verdict: dict, poa_receipt_id: str = "") -> dict:
    """Generate the complete deliverable package.

    Returns a dict with:
    - agent_md: the full agent prompt as markdown
    - policy_json: the Inner I Secure policy as JSON string
    - receipt_id: the PoA receipt ID
    - metadata: package metadata
    """
    agent_md = generate_agent_prompt(intake, verdict)
    policy = generate_policy(intake)
    policy_json = json.dumps(policy, indent=2)

    return {
        "agent_md": agent_md,
        "policy_json": policy_json,
        "receipt_id": poa_receipt_id,
        "metadata": {
            "agent_name": intake.agent_name,
            "purpose": intake.purpose,
            "audience": intake.audience or "general",
            "verdict": verdict.get("verdict", "N/a"),
            "composite": verdict.get("composite", 0),
            "truth_score": verdict.get("truth_score", 0),
            "neighbor_score": verdict.get("neighbor_score", 0),
            "fruit_score": verdict.get("fruit_score", 0),
            "mammon_score": verdict.get("mammon_score", 0),
            "service_score": verdict.get("service_score", 0),
        },
    }
